name: Android CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:     
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: npm install
              uses: Jaid/action-npm-install@v1.2.4
              with:
                    packageManager: npm
            - name: Build with Gradle
              run: ./android/gradlew assembleDevDebug
